name: Terraform Apply

on:
  push:
    branches:
      - master
      - terraform/ecs/**
      

jobs:
  terraform:
    runs-on: [self-hosted, linux, APPE]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
    steps: 
       - name: Checkout
         uses: actions/checkout@v2  
       - name: Terraform Version
         id: version
         run: |
          terraform -v
       #- name: configure aws credentials
       #  uses: fuller-inc/actions-aws-assume-role@v1
       #  with:
       #   role-to-assume: 
       #   #role-session-name: terraform-gs
       #   aws-region: us-east-1

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: us-east-1

       - name: Run Terraform init
         run: terraform init
      
       - name: Run Terraform Apply
         run: terraform apply -auto-approve
         #continue-on-error: true
    
